### ISSUE TITLE
missing requirment? - No module named 'domains'

### ISSUE THREAD

**Issue by koeppelmann** [bh2smith/cowswap-integrations-py#4]
Hey - I tried to run the script as in the readme but it failed with:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/mkoeppelmann/Documents/Code/cowswap-integrations-py/src/main.py", line 2, in <module>
    from src.order import Order
  File "/Users/mkoeppelmann/Documents/Code/cowswap-integrations-py/src/order.py", line 10, in <module>
    import domains
ModuleNotFoundError: No module named 'domains'

Not 100% where domains should come from - it's not in the requirement.txt but I can also not find a python package called "domains"

**Comment by bh2smith** [comment]
So it seems that this may have been do to outdated dependencies but maybe also the way you were running the script.

Were you executing `python -m src.main`? because `domains` is a file in the project and its definitely there.

Unfortunately the orderbook API has changed so much since repo was first created, that it will need to be completely rewritten. I will try to find some time soon to update the project.

**Comment by bh2smith** [comment]
Closed by #6 -- thanks @fleupold

**Comment by koeppelmann** [comment]
hm... at least I now get:

ERROR: Cannot install -r requirements.txt (line 2) and eth_account==0.9.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested eth_account==0.9.0
    eip712 0.2.1 depends on eth-account<0.9 and >=0.8.0


Or am I doing something wrong:
In the readme it says:
source ./env/bin/activate
As this seemed wired (and did not work) I assumed it was a typo and:
source venv/bin/activate was meant instead?

**Comment by fleupold** [comment]
https://github.com/bh2smith/cowswap-integrations-py/pull/7 should fix this error

**Comment by anxolin** [comment]
@koeppelmann does this mean IA bots will start trading in CoW Protocol?
